Fix coercion of timestamp-millis and -micros
flipp-oss/deimos pull request #98
Opened 2020-11-25 23:17 UTC by jmccance

🚧 WIP 🚧

# Pull Request Template

## Description

Adds logic to AvroSchemaCoercer to check the logical types of fields before coercing them. For `timestamp-millis` and `timestamp-micros` logical types, do not coerce them at all and let Avro's LogicalTypes modules handle it.

Fixes #97 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Added unit tests in `avro_based_shared.rb` to verify that the affected fields are not coerced. _(These tests are still WIP, as discussed above.)_

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2020-11-25 23:18 UTC, jmccance commented
The fix itself is currently working as a monkey-patch in our application. However, I'm having issues getting the tests to work correctly. Opening as a draft in case others can share some light.

The issue seems to be that when `full_schema` gets loaded by `Avro::Schema.real_parse`, the fields' logical types get discarded. `Avro::Schema::RecordSchema.make_field_objects` seems to totally disregard them. It's unclear why this isn't an issue in our application. Perhaps schema gets loaded differently outside of this spec?

2020-11-26 14:17 UTC, dorner commented
I'm loving the contributions! ❤️ I'll pull this and take a look today.

2020-11-26 15:17 UTC, dorner commented
@jmccance Got it! The schema has to change in order to make use of logicalTypes. Currently the schema in the test looks like this:

```
        {
          'name' => 'timestamp-millis-field',
          'type' => 'long',
          'logicalType' => 'timestamp-millis'
        },
```

It needs to look like this:
```
        {
          'name' => 'timestamp-millis-field',
          'type' => {
            'type' => 'long',
            'logicalType' => 'timestamp-millis'
          }
        },
```

2020-11-26 16:37 UTC, jmccance commented
D'oh! Amazing how tests work better with valid schemas. Thanks for spotting me!

I'll get the PR updated. Might be a few days because of the holiday here.

2020-12-01 21:23 UTC, dorner requested changes
@jmccance forgot to mention this in the last PR - can you please add a line in the CHANGELOG under UNRELEASED? I should update the PR template to add a checkbox for it. Otherwise we're good to go!

2020-12-02 15:59 UTC, dorner approved these changes

2020-12-02 16:00 UTC, dorner commented
LGTM! Thanks!

2020-12-02 16:00 UTC, merged